Repository oomphinc/drupal-scaffold, pull requests merged in 2019-07, with the labels that each got.

#5 Add autoprefixer to build process
  .stylelintrc.json
  docs/coding-standards.md
  docs/gulp.md
  gulpfile.js
Labels: enhancement

#37 Porting Project Docs to Scaffold
  docs/updateing-project-dependencies.md
Labels: approved, enhancement

#38 Fix typo in doc file name
  updating-project-dependencies.md
Labels: approved, documentation, good first issue

#36 Add Views Unpublished module
  composer.json
Labels: approved, configuration, enhancement
