Repository oomphinc/drupal-scaffold, pull requests merged in 2019-02, with the labels that each got.

#21 Add zaporylie/composer-drupal-optimizations library
  composer.json
Labels: approved

#23 Update the PR template
  .github/pull_request_template.md
Labels: enhancement, help wanted

#25 Update Scaffold for Lando RC
  .lando.yml
Labels: enhancement
