Repository oomphinc/drupal-scaffold, pull requests merged in 2023-03, with the labels that each got.

#111 Issue 109/readme updates
  .gitattributes
  .gitignore
Labels: work in progress

#113 Readme updates
  README.md
Labels: documentation

#112 Add DDEV config and update readme
  .ddev/config.yaml
  README.md
  web/sites/default/settings.php
Labels: enhancement, approved, documentation
